version: '3.8'

services:
  database:
    container_name: database
    image: mysql:8.3.0
    environment:
      MYSQL_ROOT_PASSWORD: rootadmin
      MYSQL_DATABASE: restful
      MYSQL_USER: appuser
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    restart: unless-stopped
    volumes:
      - ./migrations:/docker-entrypoint-initdb.d

  restful-api:
    container_name: restful-api
    image: go-restflu-api:latest
    build:
      context: ../
      dockerfile: ./Dockerfile
    environment:
      CONFIG_NAME: prod
    ports:
      - "8080:8080"
    restart: unless-stopped
    depends_on:
      - database

volumes:
  restful-data: