version: '3.8'

services:
  database:
    image: mysql:8.3.0
    environment:
      MYSQL_ROOT_PASSWORD: rootadmin
      MYSQL_DATABASE: restful
      MYSQL_USER: appuser
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - ./migrations:/docker-entrypoint-initdb.d

  restful-api:
    image: go-restflu-api-example:v1.0.0
    build:
      context: ../
      dockerfile: ./Dockerfile
    environment:
      CONFIG_NAME: prod
    ports:
      - "8080:8080"
    depends_on:
      - database

volumes:
  restful-data: