USE `restful`;

ALTER TABLE store
    ADD COLUMN deleted_at DATETIME DEFAULT NULL;
ALTER TABLE books
    ADD COLUMN deleted_at DATETIME DEFAULT NULL;
ALTER TABLE pages
    ADD COLUMN deleted_at DATETIME DEFAULT NULL;

ALTER TABLE store
    ADD COLUMN created_at DATETIME DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE books
    ADD COLUMN created_at DATETIME DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE pages
    ADD COLUMN created_at DATETIME DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE store
    ADD COLUMN updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;
ALTER TABLE books
    ADD COLUMN updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;
ALTER TABLE pages
    ADD COLUMN updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;